### ISSUE TITLE
插件下面的案例入口，前台页面无法显示。

### ISSUE THREAD

**Issue by OceanNg529** [bufanyun/hotgo#100]
平台: Mac
软件与版本：go version go1.22.2 darwin/arm64, Mysql 8 （docker里面）
系统版本：hotgo 2.15.1

新增了个插件，但是我访问的是默认的插件，确保原版也能显示

<img width="614" alt="image" src="https://github.com/bufanyun/hotgo/assets/49863683/50110102-ff52-4113-b00f-e26e9332ce86">

目录文件也存在
<img width="375" alt="image" src="https://github.com/bufanyun/hotgo/assets/49863683/7128baba-e18f-4f2f-aac1-d5265b557983">

显示以下的错误
<img width="613" alt="image" src="https://github.com/bufanyun/hotgo/assets/49863683/b6ca7d1d-6695-42c8-a7a0-f006f0753d00">

**Comment by OceanNg529** [comment]
调试过程发现Linux没问题。只有mac和win本地部署就有以上问题

**Comment by zhangshican** [comment]
平台Mac
go version go1.22.2 darwin/arm64
创建插件后运行几秒钟后尝试直接中断进程，中断后休息几秒钟再启动，就可以正常访问了。
<img width="1087" alt="111" src="https://github.com/bufanyun/hotgo/assets/8416722/baa36313-62f2-42aa-b140-83f7452a23e5">
