### ISSUE TITLE
富文本无法上传图片

### ISSUE THREAD

**Issue by qiuyier** [bufanyun/hotgo#109]
# 版本： 2.15.1
# 描述： 上传富文本报文件无法找到，如下图所示
![image](https://github.com/bufanyun/hotgo/assets/112819346/31857ee0-051e-40ca-a802-8b1c83f3228f)
经过排查，发现富文本调用上传接口时，content-type 为 application/json导致，如下图所示
![image](https://github.com/bufanyun/hotgo/assets/112819346/4a999d2d-6f59-4ec5-874b-620134fc22bd)
![image](https://github.com/bufanyun/hotgo/assets/112819346/36d3ec9c-709f-4377-85b7-be9bb86a339d)

我在修改富文本上传接口后上传正常
```javascript
// 代码位置web/src/api/base/index.ts
export function UploadImage(params) {
  const useUserStore = useUserStoreWidthOut();
  const headers = {
    Authorization: useUserStore.token,
    uploadType: 'default',
    'Content-Type': 'multipart/form-data', // 指定 content-type
  };
  return http.request({
    url: '/upload/file',
    method: 'post',
    params,
    headers,
  });
}
```
![image](https://github.com/bufanyun/hotgo/assets/112819346/617ca7b3-e808-4340-8366-16207fe8cbd9)
![image](https://github.com/bufanyun/hotgo/assets/112819346/c6563b04-70dd-482f-abd9-1060eacc8015)

**Comment by bufanyun** [comment]
好的，可以pr下

**Comment by qiuyier** [comment]
好的，我 pr 一下
