### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by helight** [bufanyun/hotgo#11]
执行 npm install 报这个错误，感觉前端的好多组件需要升级呀
npm WARN ERESOLVE overriding peer dependency

这是我的npm版本
npm version
{
  'vue-antd-pro': '3.0.0',
  npm: '9.1.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by bufanyun** [comment]
v2.3.5版本已升级
