### ISSUE TITLE
代码生成的关系树列表 level 和 tree 字段不更新

### ISSUE THREAD

**Issue by qiuyier** [bufanyun/hotgo#110]
## 版本：

2.15.1

## 描述：

通过代码生成的关系树列表，level 字段永远为 1，tree 字段为空，如图所示
![image](https://github.com/bufanyun/hotgo/assets/112819346/d9ab96fa-957c-42b9-ade0-af21afa1f678)
追溯源码查看发现，level 和 tree 字段在生成时的确已经计算好对应的值
![image](https://github.com/bufanyun/hotgo/assets/112819346/940745ad-cc93-43dd-a877-d646d53e7857)
但问题出现在写入/修改的时候，通过 fields 方法控制修改/写入的参数，并没有 level 和 tree 字段所导致的字段忽略造成
![image](https://github.com/bufanyun/hotgo/assets/112819346/376d5848-e546-4b54-8472-3750fd572588)
![image](https://github.com/bufanyun/hotgo/assets/112819346/4a05a2e3-77b9-44ec-9903-263fdd9789fc)

**Comment by bufanyun** [comment]
好，我来修复
