### ISSUE TITLE
通过代码生成的选项树列表无法删除

### ISSUE THREAD

**Issue by qiuyier** [bufanyun/hotgo#111]
## 版本
2.15.1

## 描述
通过代码生成的选项树，点击左侧栏目中的删除，无法删除，弹出是修改的页面，如图所示
![image](https://github.com/bufanyun/hotgo/assets/112819346/198d6f4f-7afc-4cd9-b2eb-b6d376fda340)

查看生成的源码，发现删除按钮的方法实际调用编辑方法，而非删除方法
![image](https://github.com/bufanyun/hotgo/assets/112819346/800b4ceb-b1ad-4d8d-9abf-e6d48a67992e)
实际应该调用为以下方法
![image](https://github.com/bufanyun/hotgo/assets/112819346/0c2cc5ec-f067-4f3d-8530-32f11a1f4f3c)

**Comment by bufanyun** [comment]
好的，感谢反馈
