### ISSUE TITLE
通过代码生成的选项树在无 status 字段时进入页面并不会获取数据

### ISSUE THREAD

**Issue by qiuyier** [bufanyun/hotgo#112]
## 版本
2.15.1
## 描述
通过代码生成的选项树，若无 status 时，进入页面不获取数据，查看代码时并未发现`onMounted()`
![image](https://github.com/bufanyun/hotgo/assets/112819346/d5c64178-70cd-4198-9d1c-070312570ada)
![image](https://github.com/bufanyun/hotgo/assets/112819346/51fb373b-8f4d-4e51-9f86-b535ab206490)
![image](https://github.com/bufanyun/hotgo/assets/112819346/54ca6abb-aff9-45a0-bf4c-e32399761a54)
但如果附上 status 字段则会带有`onMounted()`
![image](https://github.com/bufanyun/hotgo/assets/112819346/21945312-b1c0-457c-9ea1-fe7af8368ec9)
![image](https://github.com/bufanyun/hotgo/assets/112819346/6d6b946b-0ce4-4c33-9de0-de25de18f854)

**Comment by bufanyun** [comment]
好，我看看
