### ISSUE TITLE
生成代码部分有多余代码，建议删除

### ISSUE THREAD

**Issue by chehan01** [bufanyun/hotgo#126]
![image](https://github.com/user-attachments/assets/110e866d-4832-49f4-884c-b15397bae1b2)

这里的replace，用户的开发环境中，并没有指定目录去replace，会导致爆红。

![image](https://github.com/user-attachments/assets/8b604e0e-03fb-40a8-942f-bcf6f4ef37e5)

这里的go.mod被改成了go.mod.txt，会导致table_user.go里引包失败。

testdata包下的文件是为了测试生成功能，按理不应出现在开发环境中，建议删除。

**Comment by bufanyun** [comment]
已经删除，https://github.com/bufanyun/hotgo/commit/804d5d5e59cc9e51d5d9bd91b57765ecb5794048
