### ISSUE TITLE
前端编译后访问报错，TypeError: Z2 is not a function

### ISSUE THREAD

**Issue by ajhu** [bufanyun/hotgo#128]
下着最新的版本，前端dev开发环境下没有问题，但是build之后访问会报错xxx is not a function，这是什么原因啊？没有做什么开发，clone后直接build的，build能成功
![image](https://github.com/user-attachments/assets/f0213d88-a809-4703-9a7a-a69e019676ec)
![image](https://github.com/user-attachments/assets/b100bfe2-1ef0-467c-b253-b5734acbc303)
![image](https://github.com/user-attachments/assets/77147bcc-c9c4-431c-b34b-6aa1e1e637ad)

**Comment by ccxing** [comment]
大哥 你的解决了吗 ？  我都整了两天了 还没好 急死了

**Comment by maxbad** [comment]
src/router/router-icons.ts 文件内修改一下, 增加一个函数.
```
function renderIcon(icon, props = null) {
  return () => h(NIcon, props, { default: () => h(icon) });
}
```

**Comment by maxbad** [comment]
![7867c788421eb0e842d506175c6ec758](https://github.com/user-attachments/assets/01ede3dc-db08-4f31-bdf8-611bf2cec1b1)

**Comment by ajhu** [comment]
没有解决，弄了一天，后来换回之前的版本用了，没用最新的了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixingxing ***@***.***&gt;
发送时间: 2024年8月10日 15:14
收件人: bufanyun/hotgo ***@***.***&gt;
抄送: ajhu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bufanyun/hotgo] 前端编译后访问报错，TypeError: Z2 is not a function (Issue #128)





 
大哥 你的解决了吗 ？  我都整了两天了 还没好 急死了

**Comment by ajhu** [comment]
好的，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: maxbad ***@***.***&gt;
发送时间: 2024年8月10日 21:25
收件人: bufanyun/hotgo ***@***.***&gt;
抄送: ajhu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bufanyun/hotgo] 前端编译后访问报错，TypeError: Z2 is not a function (Issue #128)





 
src/router/router-icons.ts 文件内修改一下

**Comment by ccxing** [comment]
已经好了

**Comment by ajhu** [comment]
修改的哪儿啊？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixingxing ***@***.***&gt;
发送时间: 2024年8月15日 10:56
收件人: bufanyun/hotgo ***@***.***&gt;
抄送: ajhu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bufanyun/hotgo] 前端编译后访问报错，TypeError: Z2 is not a function (Issue #128)

**Comment by ccxing** [comment]
![image](https://github.com/user-attachments/assets/6a896128-2967-4517-9f7d-3fed712be2a2)
npm run preview   进行打包

**Comment by ajhu** [comment]
好的，感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixingxing ***@***.***&gt;
发送时间: 2024年8月15日 11:03
收件人: bufanyun/hotgo ***@***.***&gt;
抄送: ajhu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bufanyun/hotgo] 前端编译后访问报错，TypeError: Z2 is not a function (Issue #128)
