### ISSUE TITLE
 cron.go:49: 定时任务启动失败

### ISSUE THREAD

**Issue by yccl985055** [bufanyun/hotgo#16]
- 平台: windows
- 软件与版本：golang 1.18.4.  Mysql 8.0
- 系统版本：gotho 2.3.5
错误提示:
2023-03-09 15:54:13.560 [FATA] {685cb9ff05b14a174448395dc6a7cd05} cron.go:49: 定时任务启动失败, err . 该任务没有加入任务列表:monitor
我在配置文件中查了    # 定时任务模板
    cron:
      templates:
        - group: "default"
          templatePath: "./resource/template/generate/default/cron"
在路径中没有模板, 请问一下如何 创定时任务或解决此问题，谢谢！

**Comment by bufanyun** [comment]
数据库文件未使用安装版本的
