### ISSUE TITLE
后台“数据权限”功能报错

### ISSUE THREAD

**Issue by minxinqing** [bufanyun/hotgo#19]
按照文档把代码拉下来，数据库初始化完成后，使用admin登录后台，进入“权限管理-》角色权限”页面，点击“普通管理员”角色的数据权限按钮，无响应，控制台有错误输出，如下图：
![image](https://user-images.githubusercontent.com/3809601/230583026-f028f205-5820-4906-8e0b-e8be7028bc2f.png)

此后再点击其它菜单栏也同样报错。

**Comment by minxinqing** [comment]
拉取的最新后台版本是 2.4.9，不知道与演示版本2.3.5差别在哪，演示版本中这一功能正常。

**Comment by bufanyun** [comment]
已在v2.5.3版本中修复
