### ISSUE TITLE
关于跨域无法进入首页的问题？

### ISSUE THREAD

**Issue by zhuewizz** [bufanyun/hotgo#28]
我将web和server设置了跨域，hotgo没有问题
我把server改为我自己的 跨域没有问题 认证也通过了
跳转页面时报错了,我把router.afterEach的错误打印，信息如下：
-----toto----{"fullPath":"/login?redirect=/dashboard","hash":"","query":{"redirect":"/dashboard"},"name":"Login","path":"/login","params":{},"matched":[{"path":"/login","name":"Login","meta":{"title":"登录"},"props":{"default":false},"children":[],"instances":{"default":{}},"leaveGuards":{},"updateGuards":{},"enterCallbacks":{},"components":{"default":{"__name":"index","__hmrId":"37dfd6fc","__scopeId":"data-v-37dfd6fc","__file":"D:/postgrest/msmk-admin-xf172-server/web/src/views/login/index.vue"}}}],"meta":{"title":"登录"},"redirectedFrom":{"fullPath":"/","hash":"","query":{},"name":"Root","path":"/","params":{},"matched":[{"path":"/","redirect":"/dashboard","name":"Root","meta":{"title":"Root"},"props":{},"children":[],"instances":{},"leaveGuards":{},"updateGuards":{},"enterCallbacks":{}}],"meta":{"title":"Root"},"href":"#/"},"href":"#/login?redirect=/dashboard"}
router-guards.ts:105 failed navigation Error: Avoided redundant navigation to current location: "/login?redirect=/dashboard".
    at createRouterError (vue-router.mjs:810:23)
    at pushWithRedirect (vue-router.mjs:3169:23)
    at vue-router.mjs:3203:28
    at async handleLoginResp (form.vue:258:11)
    at async form.vue:178:9

router.afterEach((to, _, failure) => {
    console.log("------toto----" +JSON.stringify(to));
    document.title = (to?.meta?.title as string) || document.title;
    if (isNavigationFailure(failure)) {
      console.log('failed navigation', failure)
    }

**Comment by zhuewizz** [comment]
谢谢作者帮我看看

**Comment by zhuewizz** [comment]
补充一下：login后 就没有调用其他接口了 我在浏览器调试工具也注意看了

**Comment by zhuewizz** [comment]
主要是我的问题 后来跟踪代码 在getinfo,需要先取得一个权限数组，再处理路由，但奇怪的是 在浏览器的网络调试中，没有看到请求，谢谢作者的工作

**Comment by bufanyun** [comment]
没有太明白你的意思，如果问题还没有解决的话可以加群：190966648
