### ISSUE TITLE
/admin/site/login 报404错误

### ISSUE THREAD

**Issue by wenson** [bufanyun/hotgo#29]
` {c08344949686631764ad62178a721954} 404 "POST http localhost:8000 /admin/site/login HTTP/1.1" 0.000, 127.0.0.1, "http://localhost:8001/admin", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

**Comment by bufanyun** [comment]
客户端代码不是最新的，检查一下
