### ISSUE TITLE
升级到github.com/gogf/gf/v2 v2.0.4后，启动报异常

### ISSUE THREAD

**Issue by songcocl** [bufanyun/hotgo#3]
{4c0b38b31526de168f5d1c35941430ae} exception recovered: runtime error: index out of range [2] with length 0 
Stack:
1.  main.main
    D:/project/iiot/iiot-core/main.go:16

**Comment by bufanyun** [comment]
重新拉一下代码，目前hotgo已同步升级到gf/v2 v2.0.4
