### ISSUE TITLE
安装文档的数据库要求和实际不一样

### ISSUE THREAD

**Issue by ihipop** [bufanyun/hotgo#79]
文档要求 MySQL >= 5.7 https://github.com/bufanyun/hotgo/blob/v2.0/docs/guide-zh-CN/start-installation.md#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82
但是提供的安装文件却是 MySQL 8.0 的字符集编码，https://github.com/bufanyun/hotgo/blob/v2.0/server/storage/data/hotgo.sql

除了字符集不同外，数据库特性上有没有使用 8.0 only的地方呢？

**Comment by clh021** [comment]
https://github.com/bufanyun/hotgo/pull/80 已经合并，应该已经解决您的问题。

**Comment by ihipop** [comment]
> #80 已经合并，应该已经解决您的问题。

感谢 其实我自己完成了这些替换的，主要的担心就是是否存在其他mysql 8.0相关特性依赖比如 8.0 特殊的语法等等。
不过目前好像是没有哈

**Comment by fhaoquan** [comment]
我已经使用mariadb ,mysql5.7都停止维护了。后面的mysql版本也不可控。
