### ISSUE TITLE
还有后续吗？

### ISSUE THREAD

**Issue by hulu20** [bufanyun/hotgo#8]
下载安装，进行测试后，发现很多功能都没有完善
1. 组织管理模块没有完善，部门管理，用户添加没有实现
2. 权限管理模块没有完善，授权普通用户单独页面访问权限，登入后， 会拥有管理员权限

**Comment by bufanyun** [comment]
由于gf2.1改进比较大，目前hotgo正在整体适配最新的gf版本，到一定程度会进行同步，欢迎pr

**Comment by bufanyun** [comment]
v2.4.2版本已更新
