### ISSUE TITLE
部门树搜索算法bug

### ISSUE THREAD

**Issue by wohenbushuang** [bufanyun/hotgo#89]
https://github.com/bufanyun/hotgo/blob/235024fc3cc8bfae29ae67690c2ebd0211e3df48/server/internal/logic/admin/dept.go#L281-L292

当搜索的部门在第三级或以下时，models中不会有pid=0的项，`s.treeList(0, models)`将返回空

## Example：
![image](https://github.com/bufanyun/hotgo/assets/15613184/d09e8eba-6ca7-4536-8573-d69517f3f581)

![image](https://github.com/bufanyun/hotgo/assets/15613184/987145c0-69bf-493d-b215-e14864f42f7e)

![image](https://github.com/bufanyun/hotgo/assets/15613184/e00a9d74-6780-4630-b905-82a184644b4c)

**Comment by bufanyun** [comment]
感谢反馈，已在v2.15.1版本中修复
