### ISSUE TITLE
分布式锁看门狗不释放协程，内存泄漏bug

### ISSUE THREAD

**Issue by it00021hot** [bufanyun/hotgo#92]
startWatchDog函数中调用了l.wg.Wait()，但是并没有Done()，导致协程无法退出

**Comment by bufanyun** [comment]
感谢反馈，已在v2.15.1版本中修复，请查看：https://github.com/bufanyun/hotgo/blob/v2.0/server/internal/library/hgrds/lock/lock_test.go#L145
