### ISSUE TITLE
hotgo的logic层里do对象的使用

### ISSUE THREAD

**Issue by WaterCool8258** [bufanyun/hotgo#94]
发现hotgo的logic在操作数据的时候，并没有使用到do对象
（gf开发工具生成的do对象用于查询、修改、写入等操作时对操作字段的自动nil过滤。但我在开发的时候，遇到过需要将mysql里数据值设置为null的情况，这个时候用do实现不了，只能用map）

我想请教下hotgo不用do，是出于什么样的考虑，单纯的想探讨一下设计，没有其他意思

**Comment by bufanyun** [comment]
没有什么考虑，就是单纯没用😊
